fix: build documentation

diff --git a/.github/workflows/build_documentation.yml b/.github/workflows/build_documentation.yml
--- a/.github/workflows/build_documentation.yml
+++ b/.github/workflows/build_documentation.yml
@@ -1,37 +1,62 @@
-name: Make documentation
+# from https://github.com/ammaraskar/sphinx-action-test/blob/master/.github/workflows/default.yml
+name: CI
 
 on:
   push:
-    branches: [ main ]
-  pull_request:
-    branches: [ main ]
+    branches:    
+      - main
 
 jobs:
   build:
-    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
-    # You can convert this to a matrix build if you need cross-platform coverage.
-    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
+
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v1
+    # Standard drop-in approach that should work for most people.
+    - uses: ammaraskar/sphinx-action@master
       with:
-        fetch-depth: 0
-
+        docs-folder: "docs/"
+    # Example of using a custom build-command.
+    - uses: ammaraskar/sphinx-action@master
+      with:
+        build-command: "sphinx-build -b html . _build"
+        docs-folder: "docs2/"
+    # Grabbing custom dependencies and building as a pdf.
+    - uses: ammaraskar/sphinx-action@master
+      with:
+        pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended"
+        build-command: "make latexpdf"
+        docs-folder: "docs2/"
+    # Great extra actions to compose with:
+    # Create an artifact of the html output.
+    - uses: actions/upload-artifact@v1
+      with:
+        name: DocumentationHTML
+        path: docs/_build/html/
+    # Create an artifact out of the previously built pdf.
+    - uses: actions/upload-artifact@v1
+      with:
+        name: Documentation
+        path: docs2/_build/latex/pdfexample.pdf
+    # Publish built docs to gh-pages branch.
+    # ===============================
     - name: Commit documentation changes
-         run: |
-           git clone https://github.com/Becheler/quetzal.git --branch gh-pages --single-branch gh-pages
-           cp -r docs/_build/html/* gh-pages/
-           cd gh-pages
-           git config --local user.email "action@github.com"
-           git config --local user.name "GitHub Action"
-           git add .
-           git commit -m "Update documentation" -a || true
-           # The above command will fail if no changes were present, so we ignore
-           # the return code.
-       - name: Push changes
-         uses: ad-m/github-push-action@master
-         with:
-           branch: gh-pages
-           directory: gh-pages
-           github_token: ${{ secrets.GITHUB_TOKEN }}
+      run: |
+        git clone https://github.com/ammaraskar/sphinx-action-test.git --branch gh-pages --single-branch gh-pages
+        cp -r docs/_build/html/* gh-pages/
+        cd gh-pages
+        touch .nojekyll
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add .
+        git commit -m "Update documentation" -a || true
+        # The above command will fail if no changes were present, so we ignore
+        # that.
+    - name: Push changes
+      uses: ad-m/github-push-action@master
+      with:
+        branch: gh-pages
+        directory: gh-pages
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+    # ===============================
